spring:
  # 주석을 해도 안해도 상관x, 설사 틀린내용이라도. 우선순위가 docker-compose내용으로 하기 때문
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://database:3306/users_db?useSSL=false
  #    username: root
  #    password: '1234'


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/dockerbackend
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace

